[tox]
envlist = py38, py39, release

[testenv]
deps =
    pytest
commands =
    pytest

[testenv:release]
deps =
    twine
commands =
    python setup.py sdist bdist_wheel
    twine upload dist/*

[testenv:docs]
deps =
    sphinx
commands =
    sphinx-build docs docs/_build

[testenv:release]
deps =
    twine
commands =
    python setup.py sdist bdist_wheel
    twine upload dist/*