name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mypy pytest pre-commit

    - name: Run Lint
      run: pre-commit run --all-files --show-diff-on-failure

    - name: Run Tests
      run: pytest --tb=short --disable-warnings

    - name: Run Type Check
      run: mypy .